### ISSUE TITLE
ERROR:    source_sink `library(between)' does not exist

### ISSUE THREAD

**Issue by biznuge** [cushydom88/lottery-problem#1]
Tried running this on Windows 10 (Command Line) with SWI-Prolog ( version 9.0.4) and am getting the folowing error:-

~~~
> swipl -s lottery.pl -g "compute_lottery_numbers_in_range(30,61)." -t halt.
ERROR: c:/projectsfast/hobby/lotto-prolog/lottery-problem/lottery.pl:5:
ERROR:    source_sink `library(between)' does not exist
Warning: c:/projectsfast/hobby/lotto-prolog/lottery-problem/lottery.pl:5:
Warning:    Goal (directive) failed: user:use_module(library(between))
ERROR: -g compute_lottery_numbers_in_range(30,61).: test_upper_bound/3: Unknown procedure: domain/3
~~~

I can't seem to find too many references to the between library anywahere, so wondered if this is something omitted from the project in error.

Commenting out the line:
~~~
:-use_module(library(clpfd) ).
:-use_module(library(lists)).
:-use_module(library(ordsets)).
:-use_module(library(ugraphs)).
%:-use_module(library(between)).
~~~

I then get the following error when running the lottery.pl program
~~~
ERROR: -g compute_lottery_numbers_in_range(30,61).: test_upper_bound/3: Unknown procedure: domain/3
~~~

Any insight into what I might be doing wrong here would be greatly appreciated.

I arrived at this Interesting piece of research via https://www.newscientist.com/article/2384455-mathematicians-find-27-tickets-that-guarantee-uk-national-lottery-win/

Good luck.

**Comment by Midas-Coin** [comment]
You need to ?- consult('the_code.pl'). first 😁

**Comment by Midas-Coin** [comment]
imho; swiprolog might be your issue...
