### ISSUE TITLE
How to change the formulae to L(n,6,6,3) ?

### ISSUE THREAD

**Issue by Midas-Coin** [cushydom88/lottery-problem#2]
I have the code up and running; but would like to change it from L(n,6,6,2) to L(n,6,6,3) ?

I've reviewed it, but cannot see what var would 2 be / is assigned to? 

Thanks, M.

**Comment by biznuge** [comment]
@Midas-Coin - Any chance of some insight into how you got this to run? What version of Prolog / Platform etc would really help out, in the absence of any README.md to accompany this repo.

Thanks in advance.

**Comment by Midas-Coin** [comment]
You need to get SicStus & Eclipse, and setup it up for Scientific Research / Research Coding.

https://sicstus.sics.se/
You will also need to get a license for it.

I also figured out my own issue above aswell, e.g.:

```
% Compute L(n,6,6,6)
l6(N, L) :-
    Total is N*(N-1)*(N-2)*(N-3)*(N-4)*(N-5) // 720,
    %WithXSame is %X*N*(N-1)*(N-2)*(N-3)*(N-4) // 120,
    %Where l3: X = 20; l4: X = 15; l5: X = 6  
    L is N*(N-1)*(N-2)*(N-3)*(N-4)*(N-5) // 720.

%%%%%%%%%
```
